export interface EscoDataUnit {
  uri: string;
  prefLabel: {
    [key: string]: string;
  };
  notation?: string;
  broader?: string[];
  narrower?: EscoDataUnit[]; // Generated by the "tree" formats parameter
}
